FROM python:3.10-slim
WORKDIR /worker
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY celery_worker ./celery_worker
CMD ["celery", "-A", "celery_worker.tasks", "worker", "--loglevel=info"]
